theme: jekyll-theme-minimal

title: Team MythosCraft's Website
description: The website for Team MythosCraft, the creators of MythosCraft
baseurl: "/"
url: "https://team-mythoscraft.github.io" 
github_username: Team-MythosCraft
