theme: jekyll-theme-minimal

title: Team Cryptic Cosmos's Website
description: The website for Team Cryptic Cosmos, the creators of Cryptic Cosmos
baseurl: "/"
url: "https://team-cryptic-cosmos.github.io" 
github_username: Team-Cryptic-Cosmos
